title: Keygin Pro Docs
description: Documentación oficial de Keygin ERP Sync Pro

remote_theme: just-the-docs/just-the-docs

just_the_docs:
  custom_css:
    - assets/css/custom.css
  custom_js:
    - assets/js/custom.js

url: "https://hasselcode.github.io"
baseurl: "/keygin-pro-docs"

favicon_ico: "/assets/images/logo.png"

search_enabled: true

# Links arriba a la derecha
aux_links:
  "Keygin Pro Site Web":
    - "https://hasselcode.com"

# Footer
footer_content: "© 2026 Hasselcode — Keygin ERP Sync Pro"

# UI limpia como el demo oficial
color_scheme: light

plugins:
  - jekyll-remote-theme
  - jekyll-feed